spring:
  config:
    import: "optional:file:.env[.properties]"
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/urlshortener}
      auto-index-creation: true

    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  link-creation:
    company-domain: "${COMPANY_DOMAIN:}"
    company-endpoint: "${COMPANY_ENDPOINT:}"

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    properties:
      security.protocol: ${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
      sasl.mechanism: ${KAFKA_SASL_MECHANISM:PLAIN}
      sasl.jaas.config: ${KAFKA_JAAS_CONFIG:}
      session.timeout.ms: ${KAFKA_SESSION_TIMEOUT:45000}

    producer:
      key-serializer: ${KAFKA_KEY_SERIALIZER:org.apache.kafka.common.serialization.StringSerializer}
      value-serializer: ${KAFKA_VALUE_SERIALIZER:org.springframework.kafka.support.serializer.JsonSerializer}
      properties:
        spring.json.add.type.headers: false

    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:url-shortener-group}
      key-deserializer: ${KAFKA_KEY_DESERIALIZER:org.apache.kafka.common.serialization.StringDeserializer}
      value-deserializer: ${KAFKA_VALUE_DESERIALIZER:org.springframework.kafka.support.serializer.JsonDeserializer}
      properties:
        spring.json.trusted.packages: com.spring.springboot.UrlShortener.model
        spring.json.use.type.headers: false

client:
  id: ${CLIENT_ID}

virustotal:
  api-key: ${VT_API_KEY}
  analysis-url: ${VT_ANALYSIS_URL}

sendgrid:
  api_key: ${SENDGRID_API_KEY}
  verified:
    senders:
      email: ${SENDGRID_EMAIL} #the email which is verified on sendgrid and will be used as "from" email

ipinfo:
  token: ${IP_INFO_TOKEN}
jwt:
  secretKey: ${JWT_SECRET_KEY}


logging:
  level:
    org.apache.kafka: WARN
    org.springframework.kafka: WARN
